name: pharmarack_demo_app

packages:
  - packages/*
  - apps/*


scripts:
  analyze:
    exec: dart analyze

  pub_get:
    exec: flutter pub get

  clean:
    exec: flutter clean

  test:
    exec: flutter test

  integration_test:
    exec: flutter test integration_test
    failFast: true
    flutter: true
    packageFilters:
      dirExists:
        - integration_test

  build:distributor:
    run: |
      melos exec -c 6 --fail-fast -- \
        "flutter build apk"
    description: Build distributor android app.
    packageFilters:
      dirExists:
        - android
      scope: 'distributor'
  test:distributor:
      run: |
        melos exec -c 6 --fail-fast -- \
          "flutter test"
      packageFilters:
        dirExists:
          - test
        scope: 'distributor'