name: pharmarack_demo_app

packages:
  - "**"
  - packages/*
  - apps/*


scripts:
  analyze:
    exec: dart analyze
  pub-get:
    exec: flutter pub get
  flutter-analyze:
    exec: flutter analyze
  generate-coverage:
    exec: flutter test --coverage
