name: pharmarack_demo_app

packages:
  - "**"
  - packages/*
  - apps/*


scripts:
  analyze:
    exec: dart analyze
  pub_get:
    exec: flutter pub get
  build:distributor:
    run: |
      melos exec -c 6 --fail-fast -- \
        "flutter build apk"
    description: Build distributor android app.
    packageFilters:
      dirExists:
        - android
      scope: 'distributor'
  test:distributor:
      run: |
        melos exec -c 6 --fail-fast -- \
          "flutter test"
      packageFilters:
        dirExists:
          - test
        scope: 'distributor'