name: pharmarack_demo_app

environment:
  sdk: ">=2.18.0 <3.0.0"
dev_dependencies:
  flutter_test:
    sdk: flutter
  melos: ^3.1.1
  flutter_lints: ^2.0.0
dependencies:
  flutter:
    sdk: flutter
  distributor: 1.0.0+1
  retailer: 1.0.0+1

flutter:
  uses-material-design: true
