#!/bin/bash
[[ -n "${TALISMAN_DEBUG}" ]] && DEBUG_OPTS="-d"
CMD="$(git rev-parse --show-toplevel)/githooks/bin/talisman ${DEBUG_OPTS} --githook pre-push"
[[ -n "${TALISMAN_DEBUG}" ]] && echo "ARGS are $@"
[[ -n "${TALISMAN_DEBUG}" ]] && echo "Executing: ${CMD}"
${CMD}
