#!/bin/bash
[[ -n "${TALISMAN_DEBUG}" ]] && DEBUG_OPTS="-d"
CMD="
  pwd |
  cd bin |
  talisman ${DEBUG_OPTS} --githook pre-push"
[[ -n "${TALISMAN_DEBUG}" ]] && echo "ARGS are $@"
[[ -n "${TALISMAN_DEBUG}" ]] && echo "Executing: ${CMD}"
${CMD}
